[phases.setup]
nixPkgs = ["nodejs-18_x"]

[phases.install]
cmds = [
  "cd client && npm install --legacy-peer-deps --no-audit --no-fund"
]

[phases.build]
cmds = ["cd client && npm run build"]

[phases.postBuild]
cmds = [
  "npm install --production --legacy-peer-deps --no-audit --no-fund"
]

[start]
cmd = "node server.js"

[variables]
NODE_ENV = "production"
